# Generated by Django 4.0.3 on 2022-03-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='Duration',
            new_name='Duration_weeks',
        ),
    ]
